version: '3.8'

# CONFIGURACIÓN PARA MODO HOST NETWORK
# Usar cuando necesites integración completa con DHCP/DNS externos
# Comando: docker-compose -f docker-compose.host-network.yml up -d

services:
  web-ftp-server:
    build: .
    container_name: ubuntu-nginx-ftp-host
    hostname: webserver-ftp
    # Usar red del host directamente (mejor para DHCP/DNS)
    network_mode: host
    volumes:
      # Montar directorio local para archivos web (persistente)
      - ./www:/var/www/html
      # Montar directorio para archivos FTP (persistente)
      - ./ftp-data:/home/ftpuser
      # Montar logs específicos para debugging (persistente)
      - ./logs/nginx:/var/log/nginx
      - ./logs/supervisor:/var/log/supervisor
      - ./logs/vsftpd:/var/log/vsftpd
    environment:
      - FTP_USER=ftpuser
      - FTP_PASS=ftppass123
      - HOSTNAME=webserver-ftp
      - DOMAIN=local
      # Variable para indicar que estamos en modo host
      - NETWORK_MODE=host
    # En modo host, el contenedor usa la configuración DNS del host
    # Configurar DNS en el host directamente
    restart: unless-stopped
    # Privilegios adicionales para modo host
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
