version: '3.8'

services:
  web-ftp-server:
    build: .
    container_name: ubuntu-nginx-ftp
    hostname: webserver-ftp  # Nombre del host para DNS
    domainname: local        # Dominio por defecto (cambiar según tu red)
    ports:
      # Puerto HTTP para nginx
      - "80:80"
      # Puerto FTP control
      - "21:21"
      # Puerto FTP data
      - "20:20"
      # Rango de puertos para FTP pasivo
      - "21100-21110:21100-21110"
    volumes:
      # Montar directorio local para archivos web (persistente)
      - ./www:/var/www/html
      # Montar directorio para archivos FTP (persistente)
      - ./ftp-data:/home/ftpuser
      # Montar logs específicos para debugging (persistente)
      - ./logs/nginx:/var/log/nginx
      - ./logs/supervisor:/var/log/supervisor
      - ./logs/vsftpd:/var/log/vsftpd
    environment:
      - FTP_USER=ftpuser
      - FTP_PASS=ftppass123
      # Variables para configuración de red
      - HOSTNAME=webserver-ftp
      - DOMAIN=local
      - DNS_PRIMARY=192.168.1.2
      - DNS_SECONDARY=8.8.8.8
      - DNS_SERVER_IP=192.168.1.2
      - DHCP_SERVER_IP=192.168.1.2
      - SERVER_IP=192.168.1.3
    # Configuración de DNS personalizada
    dns:
      - 192.168.1.2         # DNS primario - servidor DHCP/DNS
      - 8.8.8.8             # DNS secundario (fallback)
    # Opciones adicionales de DNS
    dns_search:
      - local                # Dominio de búsqueda
    # Configuración de red avanzada
    extra_hosts:
      - "dns-server:192.168.1.2"    # IP de tu servidor DNS (cambiar)
      - "dhcp-server:192.168.1.2"   # IP de tu servidor DHCP (cambiar)
    restart: unless-stopped
    networks:
      webnet:
        # IP fija opcional (descomenta si necesitas IP estática)
        # ipv4_address: 172.20.0.10

networks:
  webnet:
    driver: bridge
    # Configuración de red personalizada para integración DHCP/DNS
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    # Opciones adicionales para el driver bridge
    driver_opts:
      com.docker.network.bridge.name: webnet-bridge
      com.docker.network.bridge.enable_ip_masquerade: "true"
